### ISSUE TITLE
Please consider using cargo-c

### ISSUE THREAD

**Issue by lu-zero** [rustls/rustls-ffi#11]
It has the logic to build header, library (including the dynamic variant) and pkg-config file.

https://crates.io/crates/cargo-c

**Comment by jsha** [comment]
Thanks for the suggestion! I'm still getting good at FFI and packaging a C library, so I want to do some of this stuff manually for now to make sure I understand how it all works. But I will keep this in mind, particularly when I need to generate a pkg-config file.

**Comment by lu-zero** [comment]
Let me know if you need help and I'll send you a pull request :)
