### ISSUE TITLE
Observation: call time costs

### ISSUE THREAD

**Issue by icing** [rustls/rustls-ffi#113]
#### Update

The initially reported numbers result from a `crustls`built without compiler optimisations, as this is the current Makefile default. When building a release version with `-O3`, the calltimes are nearly identical between Rust and C functions.

#### Original Issue
I made a test of call times when invoking `crustls` functions from my `mod_tls`code. I added 2 functions to crustls (code below) and a server global C function pointer. The server global function pointer prevents the compiler/linker to make any assumption about where it comes from. So, no inlining or LTO, as far as I know.

I called these functions in a loop 10 million times (sample code below) and got:

```
crustls /w panic_boundary:  434 ms
crustls /wo panic_boundary: 192 ms
C global function*:          10 ms 
```

Unless there is some mistake on my part (possibly, that's why I document things here), the overhead seems to play a role. 

It is negligible in functions invoked a few times on connection setup. However the API design of Rust components should probably avoid frequent calls back and forth in time critical sections when possible.

This issue is meant as an observation.

Sample code of calling:
```
  start = apr_time_now();
  for (i = 0; i < iters; ++i) {
      test_function(cc->rustls_connection, n, &n);
      if (n != 42) break;
  }
  end = apr_time_now();
  assert(i == iters);
  duration = end - start;
```

crustls test functions:
```
#[no_mangle]
pub extern "C" fn rustls_connection_try_get_int(
    conn: *mut rustls_connection,
    n: size_t,
    out_n: *mut size_t,
) {
    ffi_panic_boundary! {
        let _conn: &mut Connection = try_mut_from_ptr!(conn);
        let out_n: &mut size_t = try_mut_from_ptr!(out_n);
        *out_n = n;
    }
}

#[no_mangle]
pub extern "C" fn rustls_connection_get_int(
    conn: *mut rustls_connection,
    n: size_t,
    out_n: *mut size_t,
) {
    let _conn: &mut Connection = try_mut_from_ptr!(conn);
    let out_n: &mut size_t = try_mut_from_ptr!(out_n);
    *out_n = n;
}
```

C test function: 
```
void tls_test_get_int(rustls_connection *conn, size_t n, size_t *out_n)
{
    (void)conn;
    *out_n = n;
}
```

**Comment by alex** [comment]
I trimmed down `rustls_connection_get_int`, and its truly not doing anything besides checking if the params are 0 and then doing the assignment: https://rust.godbolt.org/z/dWTb347zP  I don't see how it can be 20x slower than `tls_test_get_int`.

For completeness though, can you try putting the null check in `test_get_int`?

I'm assuming both the Rust and C are compiled with optimizations/in release mode.

**Comment by icing** [comment]
Changed:
```
void tls_test_get_int(size_t n, size_t *out_n)
{
    if (out_n) *out_n = n;
}
```

and
```
pub extern "C" fn rustls_connection_get_int(n: size_t, out_n: *mut size_t) {
    let out_n: &mut size_t = try_mut_from_ptr!(out_n);
    *out_n = n;
}
```

and get 
```
`try` 426 ms, `raw rust` 102 ms, `raw c` 12 ms 
```

I am building `curstls` with its `make` target and the C module use `-g -O2` basically.

**Comment by icing** [comment]
Digging into the `crustls` Makefile, there is a radical change when building with `PROFILE=release`.
```
`try` 8 ms, `raw rust` 10 ms, `raw c` 10 ms 
```

This looks different.

**Comment by alex** [comment]
There we go, that's what I like to see :-)

**Comment by alex** [comment]
Without `release`, the Rust code is being compiled with no optimization in LLVM :-)

**Comment by icing** [comment]
Thanks for pointing me to this. Indeed no optimisation at all is a bit...weak. Running my load tests on that version now.

**Comment by jsha** [comment]
Very useful numbers to check, thanks! I think debug / release is a bit of a footgun. I've seen other folks get tripped up by it too. Is there anything we can do to make PROFILE=release more obvious?

**Comment by icing** [comment]
Commonly, a `release` setting is used as default in the projects I know and you have to do something extra to get a debug version. Exactly for these reasons, I assume.

**Comment by cpu** [comment]
> Update
> The initially reported numbers result from a crustlsbuilt without compiler optimisations, as this is the current Makefile default. When building a release version with -O3, the calltimes are nearly identical between Rust and C functions.

The default was switched to `release` in https://github.com/rustls/rustls-ffi/commit/132beca38a2117fe7cd2a614d82009d51450d353 so I think we can close this out :racehorse:
