### ISSUE TITLE
Run tests on Windows

### ISSUE THREAD

**Issue by tgeoghegan** [rustls/rustls-ffi#121]
#120 enables CI *builds* for Windows, but we don't yet run tests. `Makefile.Windows` needs to be updated to build `tests/*.c` instead of `src/client.c`, and there's a comment in there claiming that it doesn't work anyway due to a dependency on `epoll(7)` which we should look into.

**Comment by tgeoghegan** [comment]
Further, before investing much time into `Makefile.Windows`, and then committing to keeping it in sync with the other makefile, we should think about what level of Windows support we intend to offer and how best to do that, especially since many contributors won't have a working Windows environment to work on. `cargo-c` has been suggested (#11) but I'm not sure if it solves the problem of cross-platform compilation and running of a C test suite. Otherwise CMake might be a good choice, since besides platform specific Makefiles, we might be able to get it to spit out a .vcproj, which I suspect might be what makes life easiest for many Windows devs.

**Comment by jsha** [comment]
>  a comment in there claiming that it doesn't work anyway due to a dependency on epoll(7) which we should look into.

The test code no longer uses epoll, just plain select. So that comment can be removed.

**Comment by gvanem** [comment]
> Makefile.Windows needs to be updated to build tests/*.c instead

Yes. I contributed that some time ago. It has fallen behind. Just patch it as you see fit.
