### ISSUE TITLE
client certificate in outgoing connections

### ISSUE THREAD

**Issue by icing** [rustls/rustls-ffi#123]
Thinking about adding support in `rustls-ffi` for client configs. The `rustls` functions are there, the question is how to make them concise int the `ffi` part:

* ServerConfigs work on `CertifiedKey`s and `ffi` has functions to load these.
* a `CertifiedKey` has a `Vec<Certificate>` and a `SigningKey`
* ClientConfig's `set_single_client_cert()` gets a `Vec<Certificate>` and `PrivateKey`

I can see no way to downgrade a `SigningKey` to a `PrivateKey`. So, if applications load a `CertifiedKey` they seem to be unable to pass that to `set_single_client_cert()`. 

Correct?

**Comment by djc** [comment]
`PrivateKey` is a thin wrapper over `pub Vec<u8>`, so it seems like we could easily add some rustls-ffi API to create one?

**Comment by icing** [comment]
The question is how rustls-ffi wants to let the API user load certificate/key pairs and where it can use them.

Atm we load a `rustls_certified_key` and use that in `rustls_server_config_builder_set_certified_keys` and `rustls_client_hello_select_certified_key`.

I would like to use that also in a new `rustls_client_config_ set_single_client_cert`, but than the rust implemenation would need to convert the `SigningKey`in `rustls_certified_key` to a `PrivateKey` and I do not know how to do that.

Can you add such a method to rustls-ffi?

**Comment by djc** [comment]
In general, a `SigningKey` cannot be converted into a `PrivateKey`; that conversion really doesn't make sense in terms of the type definitions. We could potentially change rustls so that it takes a `SigningKey` directly for `with_single_cert()` on both the client and server side, I'd have to see how that works out. Do you think that would help?

**Comment by icing** [comment]
Yes, then we can work with `rusts_certified_key` in those places. That would be good.

**Comment by djc** [comment]
Hmm, I don't think it makes sense to do that. The APIs here have very different levels of visibility. The `ConfigWantsServerCert::with_single_cert()` API is called by pretty much everyone wants to run a server, so it makes sense for it to get a high-level, "shallow" type that is easy to construct and pass in. The inside of the server cert resolver is a much more rarely customization point.

I think the core idea here is that `PrivateKey` can be easily converted to a `CertifiedKey`, but not the other way around, and rustls-ffi should work with that. I suppose rustls-ffi would have to have its own `ResolvesClientCert` implementation similar to how it has its own `ResolvesServerCert` impl.

**Comment by icing** [comment]
I am not sure what you mean. Maybe a code example on how an app like `mod_tls` would provide a client certificate and key to a rustls_client_config_builder would help?

**Comment by djc** [comment]
On current rustls main, `ConfigWantsClientCert::with_single_cert()` will instantiate an `AlwaysResolvesClientCert`. `AlwaysResolvesClientCert::new()` will convert a `Vec<Certificate>` and `PrivateKey` into a `CertifiedKey`. If rustls-ffi had a local variant of `AlwaysResolvesClientCert` (which is trivial) with an API that accepted a `CertifiedKey` directly, I think your issue would be solved?

**Comment by icing** [comment]
> with an API that accepted a CertifiedKey directly

That is all I ever wanted! How that is internally translated into calls and objects is really of no interested to an API user.

**Comment by jsha** [comment]
I think this was resolved in #128. Closing optimistically; feel free to reopen if there's more work to be done.
