### ISSUE TITLE
Document default certificate behavior

### ISSUE THREAD

**Issue by kevinburke** [rustls/rustls-ffi#135]
If I try to just read and write TLS using certs that are descended from certs in my system's trust store, should they work without any additional configuration on my part? Or do I need to write some code in order to load the system certs?

I've read the documentation, the curl code in vtls/rustls.c and tests/*.c and I haven't found anything related to loading the system certs - there are examples to load from a file but not load the default set.

**Comment by djc** [comment]
No, you will need to configure explicitly what roots to trust. The simplest way to do so for Linux systems is probably to use `rustls_client_config_builder_load_roots_from_file` -- I think on Linux and other non-Darwin Unices, the "default set" is typically exposed as a file containing a bunch of PEM certificates. On macOS/iOS/Windows the situation is a whole bunch more complicated. On the Rust side, we can use [rustls-native-certs](https://github.com/rustls/rustls-native-certs/).
