### ISSUE TITLE
Support compiling crustls-demo on Windows

### ISSUE THREAD

**Issue by jsha** [rustls/rustls-ffi#15]
I recently switched from `epoll` to select to be more broadly compatible, and added macOS builds in CI: https://github.com/abetterinternet/crustls/pull/14.

I'd also like to provide Windows builds in CI. Besides the change to use `select`, it looks like I would need some additional tweaks to use winsock: https://tangentsoft.net/wskfaq/articles/bsd-compatibility.html. I haven't done network programming on Windows, and don't have a Windows dev environment yet, so it would probably take me a while. @gvanem, you provided the starter Makefile.Windows (thanks!); do you have any interest in doing the winsock changes?

**Comment by gvanem** [comment]
>  do you have any interest in doing the winsock changes?

I have ported `main.c` to Windows and it works.  With `crustls-demo.exe httpbin.org /headers`, this is the 1st output:
```
HTTP/1.1 200 OK
Date: Thu, 31 Dec 2020 10:46:33 GMT
Content-Type: application/json
Content-Length: 206
Connection: close
Server: gunicorn/19.9.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

{
  "headers": {
    "Accept": "carcinization/inevitable, text/html",
    "Host": "httpbin.org",
    "User-Agent": "crustls-demo",
    "X-Amzn-Trace-Id": "Root=1-5fedac09-12cbbab72ad35508213aed5d"
  }
}
```

Look correct?

Here is my `main.c` [main.c.txt](https://github.com/abetterinternet/crustls/files/5757094/main.c.txt) with patches.

**Comment by gvanem** [comment]
But I note there are way too many calls to `select()` in the `send_request_and_read_response()` loop. 70 calls before the 1st response is received! So maybe add a `sleep()` if nothing happened?

**Comment by jsha** [comment]
Wonderful, thank you for that patch! Yes, the output looks correct.

You're right that select is called too often. I'll add a sleep.

**Comment by gvanem** [comment]
I totally forgot about this issue, but stumbled upon it after CrusTls was added to curl.

I have now updated `src/main.c` once again. Here is what I have: [main.c.txt](https://github.com/abetterinternet/crustls/files/5957545/main.c.txt) and the diffs [main.diff.txt](https://github.com/abetterinternet/crustls/files/5957553/main.diff.txt)


Besides, the Makefile.Windows is no longer up-to-date after SChannel was added. 

But some strange issues IMHO:
* A `crustls-demo.exe www.google.com / > file1`  generates a 42.803 bytes file. Even with stdout set to binary-mode.
* A `curl -o file2 https://www.google.com`  generates a 13.305 file.

Why this large difference? AFAICS, the headers in crustls-demo doesn't look that big.

**Comment by gvanem** [comment]
And BTW, here is the `stderr` output for `crustls-demo.exe www.google.com / > t.crustls`:
```
ClientSession wants us to write_tls.
ClientSession wants us to read_tls. First we need to pull some bytes from the socket
reading from socket: EAGAIN or EWOULDBLOCK: Winsock err: 10035
ClientSession wants us to write_tls.
ClientSession wants us to read_tls. First we need to pull some bytes from the socket
reading from socket: EAGAIN or EWOULDBLOCK: Winsock err: 10035
ClientSession wants us to read_tls. First we need to pull some bytes from the socket
reading from socket: EAGAIN or EWOULDBLOCK: Winsock err: 10035
ClientSession wants us to read_tls. First we need to pull some bytes from the socket
reading from socket: EAGAIN or EWOULDBLOCK: Winsock err: 10035
ClientSession wants us to read_tls. First we need to pull some bytes from the socket
reading from socket: EAGAIN or EWOULDBLOCK: Winsock err: 10035
ClientSession wants us to read_tls. First we need to pull some bytes from the socket
EOF reading from socket
ClientSession wants us to write_tls.
ClientSession wants us to read_tls. First we need to pull some bytes from the socket
reading from socket: EAGAIN or EWOULDBLOCK: Winsock err: 10035
ClientSession wants us to write_tls.
ClientSession wants us to read_tls. First we need to pull some bytes from the socket
reading from socket: EAGAIN or EWOULDBLOCK: Winsock err: 10035
ClientSession wants us to read_tls. First we need to pull some bytes from the socket
reading from socket: EAGAIN or EWOULDBLOCK: Winsock err: 10035
ClientSession wants us to read_tls. First we need to pull some bytes from the socket
reading from socket: EAGAIN or EWOULDBLOCK: Winsock err: 10035
ClientSession wants us to read_tls. First we need to pull some bytes from the socket
EOF reading from socket
ClientSession wants us to write_tls.
ClientSession wants us to read_tls. First we need to pull some bytes from the socket
reading from socket: EAGAIN or EWOULDBLOCK: Winsock err: 10035
ClientSession wants us to write_tls.
ClientSession wants us to read_tls. First we need to pull some bytes from the socket
reading from socket: EAGAIN or EWOULDBLOCK: Winsock err: 10035
ClientSession wants us to read_tls. First we need to pull some bytes from the socket
reading from socket: EAGAIN or EWOULDBLOCK: Winsock err: 10035
ClientSession wants us to read_tls. First we need to pull some bytes from the socket
EOF reading from socket
```
A bit too many `WSAEWOULDBLOCK`?

**Comment by jsha** [comment]
This is done.
