### ISSUE TITLE
rustls_version has wrong description in header

### ISSUE THREAD

**Issue by bagder** [rustls/rustls-ffi#168]
This is a snippet from the current git main head:
~~~c
/**
 * Write the version of the crustls C bindings and rustls itself into the
 * provided buffer, up to a max of `len` bytes. Output is UTF-8 encoded
 * and NUL terminated. Returns the number of bytes written before the NUL.
 */
struct rustls_str rustls_version(void);
~~~

The description does not match the prototype!

**Comment by bagder** [comment]
I think the prototype makes it fairly clear how it actually works. Except for the lifetime of the returned data. Should it be freed/returned somehow after use?

**Comment by icing** [comment]
It does a `struct` copy, so you are concerned about the contained `char*`, I guess. In the current implementation, it points to a static string. Adding a word in the documentation about that would be good.

**Comment by bagder** [comment]
> you are concerned about the contained char*, I guess

Yes exactly!

**Comment by gvanem** [comment]
I had the same issue with the latest Rustls-FFI. I just added a `-DUSE_RUST_FFI` to handle this breaking ABI change:
```c
#ifdef USE_RUSTLS_FFI
  #include <rustls.h>

  #define rustls_client_config_builder_set_protocols  rustls_client_config_builder_set_alpn_protocols
  #define rustls_connection_get_alpn_protocol         rustls_connection_alpn_protocol
  #define rustls_version                              rustls_ffi_version
  static size_t rustls_ffi_version (char *buffer, size_t size);
#else
  #include <crustls.h>
 ...

const struct Curl_ssl Curl_ssl_rustls = {
  { CURLSSLBACKEND_RUSTLS, "rustls" },
  ...
  rustls_version,                  /* version */
 ...

#ifdef USE_RUSTLS_FFI
#undef rustls_version
static size_t rustls_ffi_version (char *buffer, size_t size)
{
  struct rustls_str ver = rustls_version();
  return msnprintf(buffer, size, "%.*s", ver.len, ver.data);
}
#endif
```

Now `curl -V` gives me this strange version: `(crustls/0.7.1/rustls/0.20.0)`.

**Comment by kevinburke** [comment]
Yikes! This is my fault, I will take a look in about one hour.
