### ISSUE TITLE
Windows: error[E0658]

### ISSUE THREAD

**Issue by gvanem** [rustls/rustls-ffi#169]
When using a heavily modified [Makefile.Windows](https://github.com/rustls/rustls-ffi/blob/main/Makefile.Windows),
I got this error from `rustc` (?):
```
cargo build --color never --release --target i686-pc-windows-msvc
    Updating crates.io index
  Downloaded libc v0.2.106ining bytes: 211.3 KB
  Downloaded 1 crate (554.8 KB) in 1.43s..
   Compiling cc v1.0.71
   Compiling winapi v0.3.9
   Compiling untrusted v0.7.1
   Compiling spin v0.5.2
   Compiling log v0.4.14
   Compiling libc v0.2.106
   Compiling cfg-if v1.0.0
   Compiling rustls-ffi v0.7.1 (F:\MingW32\src\inet\Crypto\Rustls)
   Compiling base64 v0.13.0               ] 0/24: rustls-ffi(build.rs), log(build.rs), cc, spin, untrusted, libc(b...
   Compiling rustls-pemfile v0.2.1        ] 3/24: rustls-ffi(build.rs), base64, log(build.rs), cc, libc(build.rs),...
   Compiling ring v0.16.20=>             ] 13/24: libc, winapi, log, cc
   Compiling webpki v0.22.0=======>      ] 19/24: ring
   Compiling sct v0.7.0
   Compiling rustls v0.20.0=======>      ] 19/24: webpki, sct, ring
error[E0658]: or-patterns syntax is experimental: rustls-ffi
  --> src\error.rs:51:17
   |
51 | /                 Error::InvalidCertificateData(_)
52 | |                 | Error::InvalidCertificateEncoding
53 | |                 | Error::InvalidCertificateSignature
54 | |                 | Error::InvalidCertificateSignatureType
55 | |                 | Error::InvalidSct(_),
   | |______________________________________^
   |
   = note: see issue #54883 <https://github.com/rust-lang/rust/issues/54883> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `rustls-ffi`
```
What's this? I know nothing about Rust/Cargo. Perhaps my Cargo/rustc is too old?
* `rustc -v   -> rustc 1.52.1 (9bc8c42bb 2021-05-09)`
* `cargo -V  -> cargo 1.52.0 (69767412a 2021-04-21)`

I just wanted to try `rustls_ffi.lib` in libcurl. But that seems impossible now for other reasons too (besides this).

**Comment by gvanem** [comment]
Doing a `rustup update` seemed to have fixed the issue. No idea why really. 
But now my versions are:
* `rustc -v  -> rustc 1.56.1 (59eed8a2a 2021-11-01)`
* `cargo -V -> cargo 1.56.0 (4ed5d137b 2021-10-04)`

So IMHO, Rustls could perhaps check these versions instead of such obscure `error[E0658]` message?

**Comment by jsha** [comment]
Thanks for pointing this out! Indeed, to use or-patterns we should set a "minimum supported Rust version." However, I'd rather remove the or-patterns for now and support a wider range of Rust versions, at least until or-patterns have been supported for longer.

**Comment by jsha** [comment]
By the way, to explain the error a bit more: "or-patterns" is a feature that was stabilized in Rust 1.53: https://blog.rust-lang.org/2021/06/17/Rust-1.53.0.html#or-patterns. Most likely you were on Rust 1.52 or previous, which is why you got that error.

Pull request up at #170.
