### ISSUE TITLE
Implement TryFrom<u32> for rustls_error

### ISSUE THREAD

**Issue by jsha** [rustls/rustls-ffi#198]
In #195, we added a `TryFrom<u32>` for rustls_error by way of a derive macro in the num_enum package. It would be nice not to need the extra dependency, though. We should investigate ways to do this transformation ourselves, in a way that ensures we cover all numeric codes and match them to the correct enum variant.

**Comment by cpu** [comment]
We replaced `num_enum` with https://github.com/rustls/rustls-ffi/pull/322/commits/7c12430af45fccfa57a9c251aa8967eb86a1f228 so I think we can call this one done :tm:
