### ISSUE TITLE
no ALPN protocol sent by client connection

### ISSUE THREAD

**Issue by icing** [rustls/rustls-ffi#204]
AFAICT, the ALPN protocol set by mod_tls on proxy connection is not seen in the client hello arriving at the contacted server.

my code sets `h2` as ALPN protocol via:
```
            rr = rustls_client_config_builder_set_alpn_protocols(builder,
                (rustls_slice_bytes*)rustls_protocols->elts, (size_t)rustls_protocols->nelts);
            if (RUSTLS_RESULT_OK != rr) goto cleanup;
```

but the contacted server connection does not see it.

This (with change method names, of course) used to work in previous versions.

Anything additional info I can provide, please do not hesitate to ask.

**Comment by jsha** [comment]
I've confirmed this is a bug with a local patch to server.c. Thanks for reporting! I'll dig into it.

**Comment by jsha** [comment]
I've found this issue and am working on a PR.
