### ISSUE TITLE
Improve handling for "no roots in server config"

### ISSUE THREAD

**Issue by jsha** [rustls/rustls-ffi#217]
Right now, if you call `rustls_server_config_builder_build` on a config builder where no cert resolver has been set, it will return NULL. This is a little inconsistent with other functions, where returning NULL is reserved for panics or null inputs.

Instead we should do one of two things:

 - Make cert resolver a mandatory argument to `rustls_server_config_builder_new` and `rustls_server_config_builder_new_custom`, or
 - Make `rustls_server_config_builder_build()` take an output parameter to write the built server config, and return a rustls_result, which may return a new error value RUSTLS_RESULT_NO_CERT_RESOLVER.

**Comment by cpu** [comment]
> Make rustls_server_config_builder_build() take an output parameter to write the built server config, and return a rustls_result, which may return a new error value RUSTLS_RESULT_NO_CERT_RESOLVER.

The 0.14.0 release changed the server config builder to use an out-param, but we're currently returning a `RUSTLS_RESULT_GENERAL` error for the case described here:
https://github.com/rustls/rustls-ffi/blob/eb3ccfa8ccaf254ce69a3d574acbc85344870033/src/server.rs#L356-L360

 I will open a fix to use a better error result.
