### ISSUE TITLE
Create a pkg-config file

### ISSUE THREAD

**Issue by jsha** [rustls/rustls-ffi#220]
As part of our build process, we should produce a .pc file indicating where the library and includes are, and what other libraries must be linked with it.

Some documentation: https://people.freedesktop.org/~dbn/pkg-config-guide.html

**Comment by thesamesam** [comment]
https://github.com/rustls/rustls-ffi/pull/82 would really make life a lot easier for distributions interested in looking at mod_tls & rustls. For one, it'd solve .pc and dynamic libraries for anyone who wants them.

**Comment by lu-zero** [comment]
I can redo the patchset if there is interest on it.

**Comment by cpu** [comment]
A cargo-c generated pkg-config file is available as of [v0.12.1](https://github.com/rustls/rustls-ffi/releases/tag/v0.12.1) :tada:
