### ISSUE TITLE
Remove rustls_result return value from rustls_server_config_builder_set_persistence

### ISSUE THREAD

**Issue by jsha** [rustls/rustls-ffi#229]
This function is currently: https://github.com/rustls/rustls-ffi/blob/78736fb730ffedc6bbd8acf70aa3ab08ba2be467/src/server.rs#L654-L675

Note that the only possible error return cases are that the inputs were NULL. Our API guidelines state that in such a case, we don't bother to return a rustls_result (and make the user check it), but instead do nothing and return void.

**Comment by cpu** [comment]
This looks easy to fix, but I'm not sure it's worth breaking semver for. In the primary rustls repo we have a `next-major-release` label for this. I've created the same here and applied it to this issue so we can think about knocking it out with the next big rustls update.
