### ISSUE TITLE
Make it easier to inspect a rustls_str

### ISSUE THREAD

**Issue by kevinburke** [rustls/rustls-ffi#239]
I'm writing a test in Rust that is trying to check a rustls_str, and it's trickier because it's difficult to print the contents of the str to the console. 

It might be nice to implement one of

- #[derive(Debug)] for that struct
- a method to convert a rustls_str back into a Rust str
- std::fmt::Display for that struct. 

Open to any of these that you think would be best.

**Comment by jsha** [comment]
Let's give it a `#[derive(Debug)]`

**Comment by kevinburke** [comment]
Hmmm... if we add that, I get

```
rustls_str { data: 0x1027f29b4, len: 4, phantom: PhantomData }
```

when I try to print using debug formatting:

```rust
    #[test]
    fn test_rustls_str_debug() {
        let s = "abcd";
        let rs: rustls_str = s.try_into().unwrap();
        let mut buf = String::new();
        write!(buf, "{:?}", rs);
        println!("{}", buf);
        assert_eq!(3, 4)
    }

```

**Comment by jsha** [comment]
Ah, right, sorry - a derived Debug won't work here, you need to implement an actual Debug implementation, which turns the pointer and len into an `&str`.

**Comment by kevinburke** [comment]
I suppose I could implement a custom Debug function and print out the string contents there..
