### ISSUE TITLE
Add a log facility

### ISSUE THREAD

**Issue by jsha** [rustls/rustls-ffi#24]
Rustls has some useful log lines. We should provide a way for C code to register a handler to receive those logs. Note that a single global handler isn't great, because this is a library. Also some downstream code (e.g. curl) may not have global state that we can hang log facilities off of.

**Comment by djc** [comment]
I asked around and found out that Mozilla uses this in their Android/iOS projects:

https://github.com/mozilla/application-services/blob/main/components/rc_log/

I know some people from the team working on that, so we could plausibly ask about publishing this to crates.io and/or forking it for our use case (I'd be okay maintaining something like that).

**Comment by jsha** [comment]
That looks potentially interesting! Another thing I've been thinking of: Can we tell Rust which symbols to export? If the global logger (https://docs.rs/log/0.4.14/src/log/lib.rs.html#349) is not exported, it means we can hook it from crustls without worrying that we are interfering with other Rust libraries.

**Comment by djc** [comment]
Hmm, I don't know much about things like exporting symbols. Wouldn't this still cause isssues if, say, curl wants to use both hyper's bindings and rustls bindings, and both want to "take" the global logger?

**Comment by jsha** [comment]
> Wouldn't this still cause isssues if, say, curl wants to use both hyper's bindings and rustls bindings, and both want to "take" the global logger?

My hope is that it wouldn't - because it would effectively make the LOGGER variable no longer truly global - there would be one visible internally in crustls, and one visible internally in hyper, and they wouldn't affect each other.

**Comment by jsha** [comment]
I made a demo of this approach, and it seems to work nicely: https://github.com/jsha/rust-private-loggers.

**Comment by jsha** [comment]
Fixed in #107
