### ISSUE TITLE
clone repository 

### ISSUE THREAD

**Issue by layanmansour** [rustls/rustls-ffi#272]
<img width="1440" alt="Screen Shot 1444-02-06 at 1 08 48 PM" src="https://user-images.githubusercontent.com/98415133/188118231-b5fd5d81-f969-4f58-9d4c-28cf184bc3bf.png">
how can I clone

**Comment by jsha** [comment]
Hi! This looks like an error message from GitHub Desktop. I can't help you with that. You should look for information at https://support.github.com/. Good luck. ❤️
