### ISSUE TITLE
Tracking issue for rustls 0.21 support

### ISSUE THREAD

**Issue by jsha** [rustls/rustls-ffi#294]
- [x] #292 
- ~~[ ] #293~~
- [x] #295
- [x] #296
- [x] #297
- [x] #304

**Comment by cpu** [comment]
Here are a couple other issues that I think will need to be handled:
* https://github.com/rustls/rustls-ffi/issues/295 
* https://github.com/rustls/rustls-ffi/issues/296
* https://github.com/rustls/rustls-ffi/issues/297

I proposed fix patches in the first two issues (but haven't opened a PR since it's an "all or nothing" type thing to get the build green). I think I might be able to make some progress on #297 if that would be helpful.

**Comment by jsha** [comment]
Yeah, if you'd like to start in on #297 that would be great!

I'll start a rustls-0.21.0 branch to accumulate fixes.

**Comment by jsha** [comment]
[Here's the initial commit on the rustls-0.21.0 branch](https://github.com/rustls/rustls-ffi/commit/9a32f7e0c5ef8712e3ec56c4cd7ca80736d8a049). From here let's do pull requests against it. I intended to make this first commit a PR but accidentally pushed straight to it. I've enabled branch protection on it now.

**Comment by cpu** [comment]
@jsha Do you want to strike https://github.com/rustls/rustls-ffi/issues/293 from the burndown list based on https://github.com/rustls/rustls-ffi/pull/301 landing? It seems like leaving the issue open for future implementation might make sense but it isn't a release blocker now.

**Comment by cpu** [comment]
I made a quick branch on top of `rustls-0.21.0` that integrates #305, #303, and #306: [cpu-0.21.0-smoketest](https://github.com/cpu/rustls-ffi/tree/cpu-0.21.0-smoketest) to see if CI would build :green_circle:. 

[The results](https://github.com/cpu/rustls-ffi/actions/runs/4502783181) were promising, only one task of the [Windows CMake, Debug configuration](https://github.com/cpu/rustls-ffi/actions/runs/4502783181/jobs/7925091632) job failed for ["check static library list"](https://github.com/cpu/rustls-ffi/actions/runs/4502783181/jobs/7925091632): 

```
Run python tests/verify-static-libraries.py
got unexpected list of native static libraries, fix or update README: advapi32.lib credui.lib kernel32.lib secur32.lib kernel32.lib advapi32.lib userenv.lib kernel32.lib kernel32.lib ws2_32.lib bcrypt.lib msvcrt.lib legacy_stdio_definitions.lib instead of advapi32.lib credui.lib kernel32.lib secur32.lib legacy_stdio_definitions.lib kernel32.lib advapi32.lib userenv.lib kernel32.lib kernel32.lib ws2_32.lib bcrypt.lib msvcrt.lib legacy_stdio_definitions.lib
Error: Process completed with exit code [1](https://github.com/cpu/rustls-ffi/actions/runs/4502783181/jobs/7925091632#step:6:1).
```

**Comment by cpu** [comment]
> only one task of the Windows CMake, Debug configuration job failed for "check static library list":

Here's a potential fix: https://github.com/rustls/rustls-ffi/pull/307 That was the last change required to get the branch passing.

**Comment by cpu** [comment]
We're done! :tada:

**Comment by jsha** [comment]
Yay! Thanks for all your work on this.
