### ISSUE TITLE
Update doc links for 0.21

### ISSUE THREAD

**Issue by jsha** [rustls/rustls-ffi#304]
Our documentation links out to rustls documentation for many things. For instance, `rustls_client_config_builder` links to https://docs.rs/rustls/0.20.0/rustls/struct.ConfigBuilder.html. We should update these links for the 0.21 release.

While we're at it, we should consider what version to link to:

  1. Link to the exact version of rustls we currently depend on. For consistency, this requires updating all doc links each time we bump the version of rustls, which we haven't done consistently so far.
  2. Link to `/latest/`. This stays up-to-date but will result in 404s if a future semver-incompatible version of rustls removes something we link to.
  3. Link to `/~0.21/`. This is a [special docs.rs redirection](https://docs.rs/about/redirections) that will always link to the latest version in the `0.21` series.

So far I like (2) best. The issue of future breakage is a fairly small one, and linking to `/latest/` is nice and simple.

**Comment by cpu** [comment]
Fixed with #306.

@jsha I can't close this one because I didn't open it. Could you hit the button?
