### ISSUE TITLE
checking for pkg-config along ... checking for rustls version >= 0.8.2... FAILED no" apache

### ISSUE THREAD

**Issue by davideperson** [rustls/rustls-ffi#314]
hi i'm having problem  make a pre-check of source code of latest version of httpd available httpd 2.4.57

any idea how to fix it ?

**Comment by jsha** [comment]
I've moved this issue to the rustls-ffi repository.

Here's the snippet from the linked apache.txt:

```
checking whether to enable mod_tls... checking dependencies
checking for rustls... checking for user-provided rustls base directory... none
checking for pkg-config along ... checking for rustls version >= 0.8.2... FAILED
no
checking whether to enable mod_tls... no (disabled)
```

@davideperson in your setup details, I don't see any step where you built and installed rustls-ffi. Have you done that?

@icing actually there's an 0.10.0 release tagged as of March 29: https://github.com/rustls/rustls-ffi/releases/tag/v0.10.0. But that's via the tag mechanism; I did not create a GitHub Release for it. I'll do that now.

**Comment by icing** [comment]
Ah, thanks for making the release visible. I‘ll take that out for a spin next week. Am 29.04.2023 um 00:09 schrieb Jacob Hoffman-Andrews ***@***.***>:﻿
I've moved this issue to the rustls-ffi repository.
Here's the snippet from the linked apache.txt:
checking whether to enable mod_tls... checking dependencies
checking for rustls... checking for user-provided rustls base directory... none
checking for pkg-config along ... checking for rustls version >= 0.8.2... FAILED
no
checking whether to enable mod_tls... no (disabled)

@davideperson in your setup details, I don't see any step where you built and installed rustls-ffi. Have you done that?
@icing actually there's an 0.10.0 release tagged as of March 29: https://github.com/rustls/rustls-ffi/releases/tag/v0.10.0. But that's via the tag mechanism; I did not create a GitHub Release for it. I'll do that now.

**Comment by davideperson** [comment]
> I've moved this issue to the rustls-ffi repository.
> 
> Here's the snippet from the linked apache.txt:
> 
> ```
> checking whether to enable mod_tls... checking dependencies
> checking for rustls... checking for user-provided rustls base directory... none
> checking for pkg-config along ... checking for rustls version >= 0.8.2... FAILED
> no
> checking whether to enable mod_tls... no (disabled)
> ```
> 
> @davideperson in your setup details, I don't see any step where you built and installed rustls-ffi. Have you done that?
> 
> @icing actually there's an 0.10.0 release tagged as of March 29: https://github.com/rustls/rustls-ffi/releases/tag/v0.10.0. But that's via the tag mechanism; I did not create a GitHub Release for it. I'll do that now.

thanks all  for the help , i've tried to install rustls using command cargo install rustls on linux, but downloading source code from https://github.com/rustls/rustls-ffi and build it up helped me fix the error on previous log of apache.txt i've posted
checking for pkg-config along ... checking for rustls version >= 0.8.2... FAILED  

now i received 

checking for rustls... checking for user-provided rustls base directory... none
checking for pkg-config along ... checking for rustls version >= 0.8.2... OK
yes

**Comment by davideperson** [comment]
after i've run this command on httpd source code 

**./configure --enable-ssl  --enable-so  --with-mpm=event  --with-included-apr  --prefix=/etc/httpd**

i've tried to build up latest apache version with command **make && make install**

now i have this is  error:


tls_core.c: In function 'extract_client_hello_values':
tls_core.c:510:16: error: 'rustls_client_hello' {aka 'const struct rustls_client_hello'} has no member named 'sni_name'; did you mean 'server_name'?
     if (hello->sni_name.len > 0) {
                ^~~~~~~~
                server_name
tls_core.c:511:57: error: 'rustls_client_hello' {aka 'const struct rustls_client_hello'} has no member named 'sni_name'; did you mean 'server_name'?
         cc->sni_hostname = apr_pstrndup(c->pool, hello->sni_name.data, hello->sni_name.len);
                                                         ^~~~~~~~
                                                         server_name
tls_core.c:511:79: error: 'rustls_client_hello' {aka 'const struct rustls_client_hello'} has no member named 'sni_name'; did you mean 'server_name'?
         cc->sni_hostname = apr_pstrndup(c->pool, hello->sni_name.data, hello->sni_name.len);
                                                                               ^~~~~~~~
                                                                               server_name
make[4]: *** [/home/httpd/httpd-2.4.57/build/rules.mk:212: tls_core.slo] Error 1
make[4]: Leaving directory '/home/httpd/httpd-2.4.57/modules/tls'
make[3]: *** [/home/httpd/httpd-2.4.57/build/rules.mk:117: shared-build-recursive] Error 1
make[3]: Leaving directory '/home/httpd/httpd-2.4.57/modules/tls'
make[2]: *** [/home/httpd/httpd-2.4.57/build/rules.mk:117: shared-build-recursive] Error 1
make[2]: Leaving directory '/home/httpd/httpd-2.4.57/modules'
make[1]: *** [/home/httpd/httpd-2.4.57/build/rules.mk:117: shared-build-recursive] Error 1
make[1]: Leaving directory '/home/httpd/httpd-2.4.57'
make: *** [/home/httpd/httpd-2.4.57/build/rules.mk:75: all-recursive] Error 1

**Comment by icing** [comment]
I made the necessary changes in apache's `trunk` and `2.4.x` branches and configure also checks for a more recent rustls-ffi version.

**Comment by davideperson** [comment]
i've tried to create httpd service and i receive this error

/etc/httpd/bin/httpd: error while loading shared libraries: libaprutil-1.so.0: failed to map segment from shared object

any idea?


[Unit]
Description=The Apache HTTP Server
After=network.target

[Service]
Type=forking
ExecStart=/etc/httpd/bin/apachectl -k start
ExecReload=/etc/httpd/bin/apachectl -k graceful
ExecStop=/etc/httpd/bin/apachectl -k graceful-stop
PIDFile=/etc/httpd/logs/httpd.pid
PrivateTmp=true
Restart=on-failure
RestartSec=10
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target

**Comment by cpu** [comment]
I don't believe there's any action left to take in this repo so I'm going to close this issue.
