### ISSUE TITLE
Format C code with clang-format

### ISSUE THREAD

**Issue by ctz** [rustls/rustls-ffi#327]
We have a checked-in `.clang-format`, so let's:

- run that in CI (`clang-format --dry-run --Werror ` on all .c/.h files), and expose that as `make format-check` or something
- let people run it locally with `make format`?

I suggest that we exclude `src/rustls.h` from this because it's already the subject of format rules from cbindgen?

**Comment by cpu** [comment]
I don't mind picking up this issue but it might be nice to land some of the open PRs first to avoid a lot of churn rebasing each branch afterwards.

**Comment by cpu** [comment]
https://github.com/rustls/rustls-ffi/pull/329
