### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by jprjr** [rustls/rustls-ffi#45]
Hi there, I just noticed I couldn't find licensing information in this repository.

**Comment by sagebind** [comment]
This is also a blocker for using rustls-ffi as a dependency in https://github.com/alexcrichton/curl-rust/pull/374 until we know absolutely that the license will be compatible.

**Comment by jsha** [comment]
👍🏻 https://github.com/rustls/rustls-ffi/pull/117
