### ISSUE TITLE
Rename `_config_builder_` functions to just `_config_`

### ISSUE THREAD

**Issue by jsha** [rustls/rustls-ffi#59]
I'm considering some renames. Specifically, we have all these functions named rustls_{client_server}_config_builder_foo. I introduced the "builder" concept to distinguish a ServerConfig from Arc<ServerConfig> without making the C user think about Rust's Arc type. But this didn't work out - to understand how these things work, you need to know a little about what `Arc` is doing, and we explain it in the comments.

We could make our function names a little shorter, and map more cleanly onto Rust types and names, if we called the `config_builder` just the `config`, and called the thing you finally build it into `arc_config`. So for instance:

```rust
struct rustls_server_config;
struct rustls_arc_server_config;

struct rustls_server_config* rustls_server_config_new();
const struct rustls_arc_server_config* rustls_arc_server_config_new(rustls_server_config*);
```

This would be an API break, but [we are still at semver major 0 so that's okay](https://semver.org/#spec-item-4):

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

I'm interested in input on this!

**Comment by icing** [comment]
A clearer separation between `builder` and `config` would be helpful. Atm there is no `builder_free` as it is expected to always be morphed into a `config`. But building can fail which would leave memory leaking. Also morphing a `builder` into a `config` can now never fail, meaning there can never be an incomplete build.

Also, during my work on OCSP functions, we encounter some disadvantages of the current approach. We have now 2 builder functions that install a `ResolvesServerCert` implementation. Both of these need an optional `OcspProvider` adding ocsp bytes to the chosen `CertifiedKey`. But the builder cannot be supplied with such a thing before the other functions are called (it has no place to keep it), nor can an ocsp provider added afterwards, as the installed `ResolvesServerCert` instances are no longer mutable.

If we make the builder its own `struct` it can collect all settings and on construction the `server_config` assemble it all into the proper server config.

**Comment by djc** [comment]
FWIW, in rustls we're discussing moving to explicit separate config builders. These will use type states, so it might be a bit of a pain to express in C, but the notion of making the builder type separate from the config types makes sense.

As for semver compatibility, in the Rust ecosystem 0.5 and 0.6 are treated as API incompatible the same way as 1.0 and 2.0 are, so it would be surprising to Rust users that the public API just changes if the minor version number stays the same.

**Comment by jsha** [comment]
> As for semver compatibility, in the Rust ecosystem 0.5 and 0.6 are treated as API incompatible the same way as 1.0 and 2.0 are, so it would be surprising to Rust users that the public API just changes if the minor version number stays the same.

Yes, my idea here is that this would be a minor version change - 0.4 to 0.5, for instance.

> in rustls we're discussing moving to explicit separate config builders

Ah, is that https://github.com/ctz/rustls/pull/564/? In that case, I will postpone this renaming, since it's likely the "builder" name will be appropriate soon (but the functions will probably need some tweaks).

> Atm there is no builder_free as it is expected to always be morphed into a config. But building can fail which would leave memory leaking. Also morphing a builder into a config can now never fail, meaning there can never be an incomplete build.

I think it would be reasonable to add functions to free builders without building them. In general there's a question of whether a builder should generate errors as it goes, or defer all errors to the build stage (or produce errors as it goes _and_ potentially an error at build, but that's less desirable). Looks like https://github.com/ctz/rustls/pull/564/ is pursuing the "errors as it goes" approach, but with most setters infallible.

**Comment by djc** [comment]
> Ah, is that ctz/rustls#564?

Yes, that's the server-side.

**Comment by jsha** [comment]
I'm closing this as "won't fix." The `rustls_server_config_builder` and `rustls_client_config_builder` types now correspond conceptually to `ServerConfigBuilder` and `ClientConfigBuilder` in Rust, so it's nice to have their names as-is.
